### ISSUE TITLE
Same kid for different countries

### ISSUE THREAD

**Issue by NamingException** [eu-digital-green-certificates/dgca-verifier-service#30]
Hello,

I added below a phrase from [hcert_spec](https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md)

> Due to the shortening of the identifier (for space-preserving reasons) there is a slim but non-finite chance that the overall list of DSCs accepted by a validator may contain DSCs with duplicate kids. For this reason a verifier MUST check all DSCs with that kid.

When retrieving trustlist from DGCG you only save SignerInformationEntity  without country information. If two countries have same kid, we get 2 rows. 

If country A revokes/removes its DSC certificate, verifier apps won't remove the trust certificate entry for country A because its kid coincides with the kid of county B? Verifier app retrieves a list of trusted kids and removes all that are not in that list. Because of the kids coinciding for country A and B the action of country A removing its DSC certificate wont result in that entry being removed from the verifier app.

**Comment by slaurenz** [comment]
Hi @NamingException,
first off all thanks for your input. The case that there will be to certificates with the same kid, is more theoretically than likely. Nevertheless for the rare case, that a country tries to upload a certificate, with a kid, which already exists, the gateway will not accept this request. Therefore at the moment the kid is unique at the verifier service and on the apps side.

**Comment by NamingException** [comment]
Thank you for the answer. I'm also saving the country code for each certificate on the national backend and exposing it to the verifier app, so if we do get duplicate kid then the case is accounted for.
