### ISSUE TITLE
Public API to verify Green Certificates

### ISSUE THREAD

**Issue by andreapernici** [eu-digital-green-certificates/dgca-verifier-service#56]
Hi. I don't know if I'm in the right place, but I'd like to know which is the correct REPO or API to validate Green Certificates (if it exists).

We organize events and we need to verify the participant certificates. Is there something useful to automate the task?

Thanks

**Comment by daniel-eder** [comment]
Please refer to https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 - the country you are operating from is responsible for access to the trustlist to validate certificates.
