### ISSUE TITLE
certificates download schedule

### ISSUE THREAD

**Issue by louridas** [eu-digital-green-certificates/dgca-verifier-service#57]
## Your Question

In today's DGC Piloting Community meeting it was mentioned that the downloading schedule for DSCs is recommended to be set to 6 hours.

The default setting is 2 minutes. I understand that this can be adjusted by some configuration setting. Could you please provide details?

Thanks,

Panos.

**Comment by jurosens** [comment]
Hi @louridas, the property you are looking for is `dgc.certificatesDownloader.timeInterval`. It takes the fixed period as number in milliseconds (e.g. 21600000 for your suggested 6 hours). This will work for the open source version as well as the SAP specific implementation.

See implementations of [SignerCertificateDownloadService](https://github.com/eu-digital-green-certificates/dgca-verifier-service/blob/b696dafae0895a7a6dd15dd1bfa068a28c39f1df/src/main/java/eu/europa/ec/dgc/verifier/service/SignerCertificateDownloadService.java) for further details.

Best regards and please let me know if this answers your question.

**Comment by louridas** [comment]
So, to change it in the reference implementation, we should change the line:

https://github.com/eu-digital-green-certificates/dgca-verifier-service/blob/b696dafae0895a7a6dd15dd1bfa068a28c39f1df/src/main/resources/application.yml#L48

Correct?

**Comment by jurosens** [comment]
Correct.

**Comment by louridas** [comment]
Perfect thank you!
