### ISSUE TITLE
"org.eclipse.equinox.p2.iu; net.sf.eclipsecs.core 5.2.0' but it could not be found" error in eclipse

### ISSUE THREAD

**Issue by arunextasy** [eu-digital-green-certificates/dgca-verifier-service#64]
When Trying to open the code with eclipse in windows 10, Getting below error. Provide some solution please.

org.eclipse.equinox.p2.iu; net.sf.eclipsecs.core 5.2.0' but it could not be found
Cannot complete the install because one or more required items could not be found.
  Software being installed: Checkstyle configuration plugin for M2Eclipse 1.1.4.201906210825-r (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.1.4.201906210825-r)
  Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.1.4.201906210825-r (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.1.4.201906210825-r) requires 'org.eclipse.equinox.p2.iu; net.sf.eclipsecs.core 5.2.0' but it could not be found

**Comment by f11h** [comment]
Seems like a problem in your Eclipse Installation. I guess maybe the Checkstyle Plugin is missing?
But it is not a dgcg related problem.
